### ISSUE TITLE
Subtlety - Use Ampersand

### ISSUE THREAD

**Issue by davecastlevania** [sarika-arora/prj-rev-bwfs-dasmoto#2]
https://github.com/sarika-arora/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/index.html#L5

https://github.com/sarika-arora/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/index.html#L9

Use this for ampersands 

`&amp;`

**Comment by sarika-arora** [comment]
Got it. Thanks!
